version: '2.2'

services:
  postgresDb:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=karol123
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - C:/Projects/TwitchConnector/postgres:/var/lib/postgressql/data
    ports:
      - "5432:5432"